/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyAccount {
    }
    interface MyApp {
    }
    interface MyChatApp {
    }
    interface MyChatRoom {
    }
    interface MyTest {
    }
}
declare global {
    interface HTMLMyAccountElement extends Components.MyAccount, HTMLStencilElement {
    }
    var HTMLMyAccountElement: {
        prototype: HTMLMyAccountElement;
        new (): HTMLMyAccountElement;
    };
    interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {
    }
    var HTMLMyAppElement: {
        prototype: HTMLMyAppElement;
        new (): HTMLMyAppElement;
    };
    interface HTMLMyChatAppElement extends Components.MyChatApp, HTMLStencilElement {
    }
    var HTMLMyChatAppElement: {
        prototype: HTMLMyChatAppElement;
        new (): HTMLMyChatAppElement;
    };
    interface HTMLMyChatRoomElement extends Components.MyChatRoom, HTMLStencilElement {
    }
    var HTMLMyChatRoomElement: {
        prototype: HTMLMyChatRoomElement;
        new (): HTMLMyChatRoomElement;
    };
    interface HTMLMyTestElement extends Components.MyTest, HTMLStencilElement {
    }
    var HTMLMyTestElement: {
        prototype: HTMLMyTestElement;
        new (): HTMLMyTestElement;
    };
    interface HTMLElementTagNameMap {
        "my-account": HTMLMyAccountElement;
        "my-app": HTMLMyAppElement;
        "my-chat-app": HTMLMyChatAppElement;
        "my-chat-room": HTMLMyChatRoomElement;
        "my-test": HTMLMyTestElement;
    }
}
declare namespace LocalJSX {
    interface MyAccount {
    }
    interface MyApp {
    }
    interface MyChatApp {
    }
    interface MyChatRoom {
    }
    interface MyTest {
    }
    interface IntrinsicElements {
        "my-account": MyAccount;
        "my-app": MyApp;
        "my-chat-app": MyChatApp;
        "my-chat-room": MyChatRoom;
        "my-test": MyTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-account": LocalJSX.MyAccount & JSXBase.HTMLAttributes<HTMLMyAccountElement>;
            "my-app": LocalJSX.MyApp & JSXBase.HTMLAttributes<HTMLMyAppElement>;
            "my-chat-app": LocalJSX.MyChatApp & JSXBase.HTMLAttributes<HTMLMyChatAppElement>;
            "my-chat-room": LocalJSX.MyChatRoom & JSXBase.HTMLAttributes<HTMLMyChatRoomElement>;
            "my-test": LocalJSX.MyTest & JSXBase.HTMLAttributes<HTMLMyTestElement>;
        }
    }
}
